### ndarray 연산

In [14]:
import numpy as np

### 기본연산

In [15]:
#np.arange(1, 10)     # 9개 요소의 1차원 배열
arr_a = np.arange(1, 10).reshape(3, 3)    # 요소 갯수(size)와 맞춰줘야함. 괄호 안에 shape 지정
arr_b = np.full_like(arr_a, 7)

print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [16]:
# 덧셈
print(arr_a + arr_b)
print(np.add(arr_a, arr_b))

[[ 8  9 10]
 [11 12 13]
 [14 15 16]]
[[ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [17]:
# 뺄셈
print(arr_a - arr_b)
print(np.subtract(arr_a, arr_b))

[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]
[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]


In [18]:
# 곱셈
print(arr_a * arr_b)
print(np.multiply(arr_a, arr_b))

[[ 7 14 21]
 [28 35 42]
 [49 56 63]]
[[ 7 14 21]
 [28 35 42]
 [49 56 63]]


In [19]:
# 나눗셈
print(arr_a / arr_b)
print(np.divide(arr_a, arr_b))

[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]
[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]


In [25]:
# 특수연산 1 : 몫 연산
print(arr_a // arr_b)
print(np.floor_divide(arr_a, arr_b))

[[0 0 0]
 [0 0 0]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 1]]


In [24]:
# 특수연산 2 : 나머지 연산
print(arr_a % arr_b)
print(np.mod(arr_a, arr_b))

[[1 2 3]
 [4 5 6]
 [0 1 2]]
[[1 2 3]
 [4 5 6]
 [0 1 2]]


In [34]:
# 특수연산 3 : 거듭 제곱
print(arr_a ** arr_b)
print(np.power(arr_a, arr_b))

print(np.square(arr_a))  # 제곱 연산 
print(np.sqrt(arr_a))    # 제곱근 연산

[[                   1                   16                19683]
 [          4294967296   298023223876953125 -5108087961858080768]
 [ 6812400838176574343                    0  8677311020002933897]]
[[                   1                   16                19683]
 [          4294967296   298023223876953125 -5108087961858080768]
 [ 6812400838176574343                    0  8677311020002933897]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


------------------------

### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다. 
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.   (but 작은 쪽이 1이어야함.)
- 두 배열의 차원의 크기가 같거나, 하나가 1이면 브로드캐스팅이 가능하다. 
- 크기가 1인 차원은 상대 배열의 해당 차원 크기와 다를 경우 자동으로 확장 가능하다. 
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다. 

In [ ]:
result_arr = arr_a * np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]])    # shape이 일치하는 두 배열의 연산
result_arr = arr_a * np.array([5, 5, 5])   # (3,) 1차원의 요소 3  -> 차원을 맞춰주기 위해 (1,3)으로 변환 (like : np.array([[5, 5, 5]]) ) -> 값 갯수를 맞춰주기 위해 확장 (3,3)
result_arr = arr_a * np.array([5])         # (1, ) -> 차원을 맞춰주기 위해 (1,1)로 변환 -> (1, 3) -> (3, 3)으로 확장
result_arr = arr_a * 5                     # 스칼라값

print(result_arr)                          # 결과가 달라지지 않음. 

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [43]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])   #(2, 3)
arr2 = np.array([5, 10, 100])             #(3, )

arr1 + arr2

array([[  6,  12, 103],
       [  9,  15, 106]])

In [45]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])    #(2, 3)
arr2 = np.array([[100], [200]])            #(2, 1)

arr1 + arr2   #(2, 3)

array([[101, 102, 103],
       [204, 205, 206]])

In [47]:
arr1 = np.array([1, 2, 3])             # (3, )    -> (1, 3)             -> (3, 3)
arr2 = np.array([[4], [5], [6]])       # (3, 1)              -> (3, 3)               # 뒤 먼저 비교하기 때문에 먼저 증가 

arr1 + arr2    # (3, 3)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # (2, 3)
arr2 = np.array([1, 2])                   # (2, )   -> (1, 2) 

# arr1 + arr2        # value error    불가능. 

-----------------


### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 점곱은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다. 
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 행의 수가 같아야 한다. 
    - 연산 결과의 shape은 (첫 번째 행렬 A의 행 개수, 두 번째 행렬 B의 열 개수)이다. 




[[a b]           [[e f]              (a*e+b*g  a*f+b*h
 [c d]]   내적     [g h]]    ->        c*e+d*g  c*f+d*h)

In [52]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)
print(arr1 * arr2)   # 각 위치에 맞는 값들끼리 연산(기본연산)

print(np.dot(arr1, arr2))
print(np.dot(arr1, arr2).shape)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
(2, 2)


In [ ]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])                 # (2, 3)
arr4 = np.array([[7, 8], [9, 10], [11, 12]])            # (3, 2)

np.dot(arr3, arr4)   #(2, 2)             # 행*열의 합이기 때문에 2, 2

# (100, 200000) (100, 20000)  : 내적 안됨. 행의 요소와 열의 요소가 곱해진 행태로 반환하기 때문에 행, 열의 요소가 맞아야함. 

array([[ 58,  64],
       [139, 154]])

In [ ]:
# @
print(arr3 @ arr4)  # dot 연산은 아니지만 내적 시행

[[ 58  64]
 [139 154]]


In [85]:
# print(arr3 @ arr3)   # (2, 3) (2, 3) shape == 내적 안됨. 

# .T = 전치행렬 (행-열을 교환)
print(arr3.T)   # 전치 속성
print(arr3 @ arr3.T)

# matmul() (= @)  : 2차원에서는 dot처럼 사용, but 다차원에서는 matmul 사용
print(np.matmul(arr3, arr3.T))

# 다차원에서의 배열에서 행렬곱을 수행하고자 할 때는 matmul 사용 (2차원에서는 dot과 같은 기능을 수행)

[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


-----

### 연산함수 및 집계 함수 

In [64]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [66]:
# 올림
print(np.ceil(arr_float))

# 반올림
print(np.round(arr_float))

# 내림 (지정된 수(요소)보다 작은 최대 정수)
print(np.floor(arr_float))      # 음수일 때 차이남. (해당 수 보다 작은 최대 정수 반환)

# 버림 (절삭)
print(np.trunc(arr_float))

[[ 2. -5.]
 [-7. 11.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [69]:
# 절대값
np.abs(arr_negative)

array([[  1,   2],
       [100, 200]])

In [84]:
# 최대값 / 최소값
print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0))  # 행 기준
print(np.min(arr, axis=1))  # 열 기준


arr_1 = [[4, 5, 6], [8, 6, 3]]
print(np.max(arr_1, axis=0))
print(np.max(arr_1, axis=1))

6
1
[4 5 6]
[1 4]
[8 6 6]
[6 8]


In [82]:
# 합계
print(np.sum(arr))

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
21
[5 7 9]
[ 6 15]


In [80]:
# 평균
print(np.mean(arr))  #np의 함수

print(arr.mean())    #메서드
print(arr.mean(axis=0))
print(arr.mean(axis=1))

3.5
3.5
[2.5 3.5 4.5]
[2. 5.]
