# ndarray 정렬

In [1]:
import numpy as np

### 1차원 배열 정렬

In [2]:
arr = np.random.randint(1, 11, 10)
arr

array([6, 4, 2, 5, 6, 3, 6, 1, 7, 7], dtype=int32)

In [7]:
# np.sort(arr) 
# - 정열된 ndarray를 '반환'. 원본 배열에 영향을 주지 않음. 
# - 오름차순 정렬만 지원
arr = np.sort(arr)   # reverse = True 지원 X 
arr_r = np.sort(arr)[::-1]

In [ ]:
print(arr)     # python .sort 매서드는 원본 데이터에 대해 sort / sort 값을 반환하는 np.sort 함수와 다름.
print(arr_r)   # 내림차순 정렬

[1 2 3 4 5 6 6 6 7 7]
[7 7 6 6 6 5 4 3 2 1]


### 2차원 배열 정렬

In [ ]:
arr = np.random.randint(10, size=(3, 4))   # 0 이상 10 미만
arr

array([[6, 4, 7, 0],
       [1, 0, 8, 4],
       [5, 9, 4, 3]], dtype=int32)

In [ ]:
np.sort(arr)   # 열 방향 정렬 (axis 기본값 = 1)

array([[0, 4, 6, 7],
       [0, 1, 4, 8],
       [3, 4, 5, 9]], dtype=int32)

In [ ]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬) (*행과 행방향은 수직임. 행방향=행이 늘어나는 방향으로 이해하기)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[1 0 4 0]
 [5 4 7 3]
 [6 9 8 4]]
[[0 4 6 7]
 [0 1 4 8]
 [3 4 5 9]]


In [ ]:
print(np.sort(arr, axis=None))          # axis = None 축 무시 (행/열 구분없이 모든 값 정렬)      like 인덱싱 / 슬라이싱 내용
print(np.sort(arr, axis=None).shape)    # 1차원

[0 0 1 3 4 4 4 5 6 7 8 9]
(12,)


### np.argsort()
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [ ]:
arr = np.array([100, 400, 200, 300])

print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [21]:
# 블랙핑크 사라졌어...
blackpink = np.array(['제니','로제','리사','지수'])
album_sales = np.array([900,870,780,1002])

# 앨범 판매량이 많은 순으로 멤버 이름을 정렬

print(blackpink[np.argsort(album_sales)[::-1]])

['지수' '제니' '로제' '리사']


In [ ]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 7, 25], [14, 41, 30]])

print(np.sort(arr))
print(np.argsort(arr))             # axis 기본값 = 1 (열 방향 정렬)
print(np.argsort(arr, axis=1))     # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr, axis=0))     # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[   7   25 2025]
 [  14   30   41]]
[[1 2 0]
 [0 2 1]]
[[1 2 0]
 [0 2 1]]
[[1 0 0]
 [0 1 1]]
