# ndarray 병합 및 분할

In [3]:
import numpy as np

### ndarray 요소 추가 및 삭제
- ndarray는 고정 길이 배열이다. == 크기 변경이 불가하다. == 요소를 추가할 수 없다(삭제할 수 없다.) 
- * 원본이 바뀐 것이 아니라 원본에 새로운 것을 추가하여 새로운 array를 만드는 것

In [ ]:
# np.append(원본배열, 삽입한 요소) : 요소를 추가한 새로운 배열을 반환
# np.insert(원본배열, 삽입할 위치 인덱스, 삽입할 요소) : 요소를 추가한 새로운 배열을 반환

arr = np.array([10, 20, 30])

arr1 = np.append(arr, 40)          # 함수
arr2 = np.insert(arr, 1, 999)      # insert(배열, 인덱스, 값)

print(arr)                         # append, insert가 출력된 결과는 포함하지 않음
print(arr1)
print(arr2)

print(arr2 is arr)                 # 서로 일치하는지 알아보는 함수

[10 20 30]
[10 20 30 40]
[ 10 999  20  30]
False


In [ ]:
# 2차원 배열에서 insert()
arr_2d = np.arange(1, 13).reshape(3, 4)
print(arr_2d)

# np.append(arr_2d, 100)
print(np.insert(arr_2d, 1, 100))     # 요소가 제거됨. axis=None : 1차원 배열로 변환 후 요소 삽입

# 파라미터 -> 원본배열, 삽입할 위치 인덱스, 삽입할 요소, axis (0: 행 기준 / 1: 열 기준)
print(np.insert(arr_2d, 1, 100, axis=0))   # 행 기준 [1] 위치 요소에 값 부여. 다른 값은 한 줄 밀려남.
print(np.insert(arr_2d, 1, 100, axis=1))   

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[  1 100   2   3   4   5   6   7   8   9  10  11  12]
[[  1   2   3   4]
 [100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]


In [ ]:
print(np.insert(arr_2d, 1, 100, axis=1))  # 스칼라값
print(np.insert(arr_2d, 1, [100], axis=1)) # 배열 형태
print(np.insert(arr_2d, 1, [100, 200, 300], axis=1))  # 여러 값 가능
# print(np.insert(arr_2d, 1, [100, 200, 300], axis=0))  # shape의 형태와 동일하게 작성해야함. 
                                                        # 삽입하려는 값의 형태가 기존 shape에 맞지 않으면 error 발생
print(np.insert(arr_2d, 1, [100, 200, 300, 400], axis=0))

[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]
[[  1 100   2   3   4]
 [  5 200   6   7   8]
 [  9 300  10  11  12]]
[[  1   2   3   4]
 [100 200 300 400]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
# np.delete(원본배열, 삭제할 요소의 위치 인덱스): 요소를 삭제한 새로운 배열을 반환

arr = np.arange(1, 15)
arr1 = np.delete(arr, 7)     # 원본배열, 삭제할 요소의 위치 인덱스

print(arr)
print(arr1)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14]


In [ ]:
arr_2d = np.arange(1, 13).reshape(3, 4)

print(arr_2d)
print(np.delete(arr_2d, 1))            # axis=None : 1차원 배열로 변환 후 요소 삭제 
print(np.delete(arr_2d, 1, axis = 0))
print(np.delete(arr_2d, 1, axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


---

### ndarray 병합
- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [28]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [ ]:
# np.append()
print(np.append(arr1, arr2))    # axis = NOne
print(np.append(arr1, arr2, axis = 0))  # 행 방향으로 병합 (행 추가)
print(np.append(arr1, arr2, axis = 1))  # 열 방향으로 병합 (열 추가)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
# np.vstack() : axis=0 병합 (수직)
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야함. (파라미터를 하나만 받도록 만들어짐)
# 열의 개수가 같아야함.

np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
# np.hstack() : axis=1 병합 (수평)
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야함.
# 행의 개수가 같아야함.

np.hstack([arr1, arr2])

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [ ]:
# np.concatenate()
# append 와 유사하나 병합 대상 ndarray를 묶어서 전달해야하며, axis 기본값이 0임. (append = None이였음.)

# print(np.concatenate(arr1, arr2))   # 병합 대상 ndarray 묶어서 전달
print(np.concatenate((arr1, arr2)))   # axis 기본값 == 0 
print(np.concatenate((arr1, arr2), axis = 0)) 
print(np.concatenate((arr1, arr2), axis = 1)) 
print(np.concatenate((arr1, arr2), axis = None)) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


### ndarray 분할
- split()

In [41]:
arr = np.concatenate((arr1, arr2))   # 수직 방향 결합 (6,4)

# np.split(원본 배열, 분할할 개수, axis)
print(np.split(arr, 2))   # 리스트로 출력. 행 방향으로 분할(기본값 axis=0)
print(np.split(arr, 2, axis=0))   # 행 기준
print(np.split(arr, 2, axis=1))   # 열 기준

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]


In [ ]:
n = 2

# 약수로만 분할 가능

# arr의 shape (6, 4)
print(np.split(arr, n, axis=0))  # 행 기준 -> 6행 -> 1, 2, 3, 6
print(np.split(arr, n, axis=1))  # 열 기준 -> 4열 -> 1, 2, 4

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
