# ndarray 형태 변경

In [1]:
import numpy as np 

### reshape()
- 요소의 개수가 맞는 shape으로 변형 가능

In [3]:
arr = np.arange(12)
print(arr.ndim, arr.shape)

1 (12,)


In [9]:
arr = arr.reshape(3, 4)     # 요소의 개수만 맞으면 어떤 shape이라도 상관 없음. 
arr = arr.reshape(6, 2)
arr = arr.reshape(12, 1)

arr = arr.reshape(2, 2, 3)  # 요소의 개수만 맞으면 차원 변경도 가능
print(arr.ndim, arr.shape) 
print(arr)

3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
# reshape(-1) : 1차원 처리 
arr = arr.reshape(-1)  
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# reshape(a, b) -> a or b 하나가 -1 : -1인 축은 자동 계산
arr = arr.reshape(4, -1)
arr = arr.reshape(-1, 4)
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### np.ravel()
- 1차원 변환 
- np가 제공하는 함수 

In [ ]:
arr = np.ravel(arr)   # arr 원래 형태 (3, 4)
print(arr)  # 어떤 차원이든 1차원으로 변환

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### np.expand_dims()
- 차원 추가

In [19]:
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)

# print(np.expend_dims(arr_1d))  # error
print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=0).shape)
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [ ]:
arr_2d = np.array([[1, 2], [3, 4]])

print(arr_2d.shape, arr_2d)  # 2차원이기 땨문에 0, 1, 2 부여 가능

print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=0).shape) 
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=1).shape)
print(np.expand_dims(arr_2d, axis=2))
print(np.expand_dims(arr_2d, axis=2).shape)

(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


### np.squeeze()
- 차원의 값(=해당 차원의 요소 개수)이 1일 때, 차원 제거 

In [ ]:
arr = np.array([[1, 2]])
print(arr.shape)

arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr, axis=0) #0번째 차원을 대상으로 차원 제거
# arr2 = np.squeeze(arr, axis=1) # 없애려고 하는 축의 요소 개수가 1이 아니라서 error

print(arr2.shape)

(1, 2)
(2,)
