In [3]:
from sklearn.datasets import load_iris

iris_data = load_iris()
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
# input 데이터
print(iris_data.data)
# 특성명
print(iris_data.feature_names)
# label 데이터 (정답 데이터)
print(iris_data.target)
# label 명
print(iris_data.target_names)   # ['setosa' 'versicolor' 'virginica'] 각각 0, 1, 2

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [13]:
import pandas as pd
import numpy as np 

iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df['label'] = iris_data.target
iris_df.describe()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)       label
count         150.000000        150.000000  ...        150.000000  150.000000
mean            5.843333          3.057333  ...          1.199333    1.000000
std             0.828066          0.435866  ...          0.762238    0.819232
min             4.300000          2.000000  ...          0.100000    0.000000
25%             5.100000          2.800000  ...          0.300000    0.000000
50%             5.800000          3.000000  ...          1.300000    1.000000
75%             6.400000          3.300000  ...          1.800000    2.000000
max             7.900000          4.400000  ...          2.500000    2.000000

[8 rows x 5 columns]

### 최근접 이웃 분류 모델로 훈련/평가 연습하기 

In [27]:
# 데이터 전처리
# 1. 입력 - 정답 데이터 분리 
iris_length = np.array(iris_df['sepal length (cm)']) + np.array(iris_df['petal length (cm)'])
iris_width = np.array(iris_df['sepal width (cm)']) + np.array(iris_df['petal width (cm)'])

# train_input = []
# for l, w in zip(iris_length, iris_width) :    
#     train_input.append([l, w])
# train_input

from sklearn.model_selection import train_test_split
train_input, test_input, train_label, test_label = train_test_split(iris_length, iris_width, random_state=42) 
train_input.shape, test_input.shape, train_label.shape, test_label.shape

# 2. 훈련 - 평가 데이터 분리 
# train_label = [1] * len(iris_df['train_']) + [0] * len(iris_df['petal length (cm)'])
# train_label 


# 3. 정규화 




# 훈련 정답 데이터 준비

((112,), (38,), (112,), (38,))

In [ ]:
# 훈련
# from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()   #모델 객체를 만듦
kn.fit(train_input, train_label)    
kn.score(test_input, test_label)  
# kn.predict([[30, 500], [10, 5]])   

In [ ]:
# 평가 
