### **[실습] 데이터를 기반으로 배열 연산 수행**

<aside>
❓

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)
</aside>

In [12]:
import numpy as np

In [14]:
arr1 = ([[200, 340, 150, 400]])
arr2 = ([[220, 300, 180, 420]])
arr = arr1 +arr2

print(arr)
print(np.sum(arr))
print(np.mean(arr, axis=1))

[[200, 340, 150, 400], [220, 300, 180, 420]]
2210
[272.5 280. ]


### **[실습 1] 기본 산술 연산**

<aside>
❓

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

</aside>

In [19]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### [**실습 2] Dot Product**

<aside>
❓

다음 두 배열 간의 내적 연산을 수행하세요.

</aside>

In [29]:
arr1 = np.array([1, 2, 3]).reshape(3,)
arr2 = np.array([4, 5, 6]).reshape(3,)

print(arr1)
print(arr2.T)
print(arr1 @ arr2.T)
print(np.dot(arr1, arr2))

[1 2 3]
[4 5 6]
32
32


### [**실습 3] 브로드캐스팅**

<aside>
❓

아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

</aside>

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)


[[11 22 33]
 [14 25 36]]


### **[실습 4] 비교 연산 및 집계 함수 사용**

<aside>
❓

1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
</aside>

In [38]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 20])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[30 40 50]
150
50
10
30.0
